In [1]:
import numpy as np

a = np.array([1,2,3])
print(a.ndim)# ndim represents the no of nested lists in the numpy array
print(a.size)
print(a.shape)
reshaped_a = a.reshape(3, 1)
print(a)
print(reshaped_a)
print(a.dtype)

1
3
(3,)
[1 2 3]
[[1]
 [2]
 [3]]
int32


In [2]:
b=np.zeros(3)
print(b)
print(b.dtype)
print(type(b[0]))

[0. 0. 0.]
float64
<class 'numpy.float64'>


In [3]:
n = np.array([4,6,7,9,10,11,1])
print(n)
print(n.min())
print(n.max())
print(n.sum())

[ 4  6  7  9 10 11  1]
1
11
48


In [4]:
p = np.array([0,1])
q = np.array([2,3])
print("Vector1:",p)
print("Vector2:",q)
print("Vector Addition:",p+q)
print("Vector Subtraction:",p-q)
print("Hadamard Product:",p*q) #element wise product
print("Dot Product:",np.dot(p,q)) #matrix multiplication
r = np.array([0,1,2,3])
print(r*2)
print(r+1)
print(r.mean())

Vector1: [0 1]
Vector2: [2 3]
Vector Addition: [2 4]
Vector Subtraction: [-2 -2]
Hadamard Product: [0 3]
Dot Product: 3
[0 2 4 6]
[1 2 3 4]
1.5


In [5]:
x=np.array([(1,2,3),(4,5,6)])
print(x.ndim)
print(x.size)
print(x.shape)
print(x)
print(x.reshape(3,2))
#print(y)

2
6
(2, 3)
[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


In [6]:
ar = np.array([[1,2,3],[3,4,5],[6,7,8]])
print(ar)
print(ar.ndim)
print(ar.size)
print(ar.shape)
print(ar.min())
print(ar.max())
print(ar.sum())
print(ar.sum(axis=1))
print(ar.sum(axis=0))
print(ar.T)

[[1 2 3]
 [3 4 5]
 [6 7 8]]
2
9
(3, 3)
1
8
39
[ 6 12 21]
[10 13 16]
[[1 3 6]
 [2 4 7]
 [3 5 8]]


In [7]:
a1 = np.array([[1,2,3],[4,5,6]])
a2 = np.array([[1,2,3],[4,5,6]])
print(a1+a2)
print(a1-a2)
print(a1*a2)

"""vstack is short for "vertical stack". It is used to vertically stack arrays on top of each other. 
This function takes a sequence of arrays and stacks them vertically to create a single array. 
All arrays must have the same number of columns"""

print(np.vstack((a1,a2)))


"""hstack is short for "horizontal stack". It is used to horizontally stack arrays side by side. 
This function takes a sequence of arrays and stacks them horizontally to create a single array.
All arrays must have the same number of rows."""


horstack = np.hstack((a1,a2))
print(horstack)


"""ravel is used to flatten multi-dimensional arrays into a one-dimensional array.
It returns a contiguous flattened array containing all the elements of the input array. """
print(np.ravel(a1))

[[ 2  4  6]
 [ 8 10 12]]
[[0 0 0]
 [0 0 0]]
[[ 1  4  9]
 [16 25 36]]
[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]
[[1 2 3 1 2 3]
 [4 5 6 4 5 6]]
[1 2 3 4 5 6]


In [8]:
nd = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(nd.ndim)
print(nd.size)
print(nd.shape)
print(nd.dtype)
print(nd.min())
print(nd.max())
print(nd.sum())
print(nd.sum(axis=1))
print(nd.sum(axis=0))
print("\n")
print(nd)
print("\n")
print(nd[0,:])#all elements of row0
print(nd[1,:])#all elements of row1 
print(nd[2,:])#all elements of row2
print("\n")
print(nd[:,0])#all elements of col0
print(nd[:,1])#all elements of col1 
print(nd[:,2])#all elements of col2
print("\n")
print(nd[::2,::2])#corner elements
print("\n")
print(nd[0,::2])#corner elements of row0
print(nd[1,::2])#corner elements of row1 
print(nd[2,::2])#corner elements of row2
print("\n")
print(nd[::2,0])#corner elements of col0
print(nd[::2,1])#corner elements of col1
print(nd[::2,2])#corner elements of col2
print("\n")
#elements at each index
print(nd[0,0])
print(nd[0,1])
print(nd[0,2])
print(nd[1,0])
print(nd[1,1])
print(nd[1,2])
print(nd[2,0])
print(nd[2,1])
print(nd[2,2])
print("\n")
print(nd.T)

2
9
(3, 3)
int32
1
9
45
[ 6 15 24]
[12 15 18]


[[1 2 3]
 [4 5 6]
 [7 8 9]]


[1 2 3]
[4 5 6]
[7 8 9]


[1 4 7]
[2 5 8]
[3 6 9]


[[1 3]
 [7 9]]


[1 3]
[4 6]
[7 9]


[1 7]
[2 8]
[3 9]


1
2
3
4
5
6
7
8
9


[[1 4 7]
 [2 5 8]
 [3 6 9]]
